export const menuItemsData = [
  {
    id: 1,
    name: 'Mediterranean  Salad',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 650,
    img: '/images/bigBurger.png',
  },
  {
    id: 2,
    name: 'Summer Asian Slaw',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 350,
    img: '/images/bowl1.png',
  },
  {
    id: 3,
    name: 'Burger',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 650,
    img: '/images/bowl2.png',
  },
  {
    id: 4,
    name: 'white sauce pasta',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 700,
    img: '/images/bowl3.png',
  },
  {
    id: 5,
    name: 'butterfly pasta',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 550,
    img: '/images/bowl4.png',
  },
  {
    id: 6,
    name: 'tooty fruity bowl',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 570,
    img: '/images/fruits.png',
  },
  {
    id: 7,
    name: 'granola cereal bowl',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 540,
    img: '/images/granola cereal bowl.png',
  },
  {
    id: 8,
    name: 'palm bowl',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 670,
    img: '/images/kisspng-aa-na-tigela-smoothie-aa-palm-bowl-apple-j-goji-berry-5b306ffe7baf07.9992682215299010545066.png',
  },
  {
    id: 9,
    name: 'tigela smoothie',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 530,
    img: '/images/kisspng-aa-na-tigela-smoothie-breakfast-juice-health-s-acai-bowl-5b11d2604db908.6695630315278946243184.png',
  },
  {
    id: 10,
    name: 'breakfast cereal',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 550,
    img: '/images/kisspng-breakfast-cereal-pizza-muesli-meze-vegetarian-cuis-granola-5ac48d852aeb69.1891892315228307251758.png',
  }
];
